# Using `git update-index --assume-unchanged scripts/.air.toml` to let git untrack it.
root = "."
tmp_dir = ".air"

[build]
bin = './.air/go-demo'
# 开发环境
#full_bin = 'GO_ENV=dev ./.air/go-demo '
# 测试环境
full_bin = 'GO_ENV=dev ./.air/go-demo '
## Use --tags "store.db" to enable SQL query logging against our metadata db.
## Use -gcflags="all=-N -l" to disable inlining and optimization

## 构建参数 gcflags 的值这样写的原因： https://github.com/golang/vscode-go/wiki/debugging
cmd = """
  go build \
  -p=8 \
  -gcflags="all=-N -l" \
  --tags "minimal" \
  -o ./.air/go-demo main.go"""
delay = 500
exclude_dir = [
  ".air",
  "docs",
  "app",
  "proto",
  "vendor",
]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
send_interrupt = true
kill_delay = 1000
